default: &default
  adapter: sqlite3
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: cart_rules_development

test:
  <<: *default
  database: cart_rules_test